services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=emby-server